//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado_net_exam_delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string DeliveryAdress { get; set; }
        public string OrderDescription { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public double DeliveryCost { get; set; }
        public int CarrierId { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
